version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: protek_app
    ports:
      - "5001:5000"
    environment:
      - PORT=${PORT:-5000}
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      # Database
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-yourapp_db}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password123}
      - POSTGRES_DB=${POSTGRES_DB:-yourapp}
      - POSTGRES_SSLMODE=disable
      - DATABASE_URL=postgresql://${POSTGRES_USER:-yourapp_db}:${POSTGRES_PASSWORD:-password123}@db:5432/${POSTGRES_DB:-yourapp}?sslmode=disable
      # JWT
      - JWT_SECRET=${JWT_SECRET:-D8D3DA7A75F61ACD5A4CD579EDBBC}
      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      # Email
      - EMAIL_FROM=${EMAIL_FROM:-gamingafriza005@gmail.com}
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - EMAIL_NAME=${EMAIL_NAME:-Zacode}
      - SMTP_USERNAME=${SMTP_USERNAME:-muhammadazizajg@gmail.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-xigiolmeavjshrrt}
      # Rate Limiting
      - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
      - RATE_LIMIT_RPS=${RATE_LIMIT_RPS:-100}
      - RATE_LIMIT_BURST=${RATE_LIMIT_BURST:-200}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - protek_network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: protek_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-yourapp_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-yourapp}
    ports:
      - "5433:5432"   # host 5433 agar tidak bentrok dengan postgres lain di 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - protek_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yourapp_db -d yourapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  protek_network:
    driver: bridge
